apiVersion: v1
kind: Pod
metadata:
  name: svc-pod-2
  labels:
    app: test-1
spec:
  containers:
    - name: test-co-2
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP